# ============================================================
# EXACT FILE LOCATION: backend/models/interview_models.py
# ============================================================
# Phase 6/7/8 — AI Interview System database tables.
#
# Tables:
#   1. interview_sessions  — one session per candidate+job
#   2. interview_questions — AI-generated questions per session
#   3. interview_answers   — candidate answers (text or voice)
# ============================================================

from sqlalchemy import (
    Column, Integer, String, Text, Float,
    DateTime, Boolean, Enum, ForeignKey
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database.database import Base
import enum


# ============================================================
# Session status lifecycle
# ============================================================
class SessionStatus(str, enum.Enum):
    PENDING    = "PENDING"      # Questions generated, not started
    IN_PROGRESS = "IN_PROGRESS" # Candidate is answering
    COMPLETED  = "COMPLETED"    # All answers submitted
    EVALUATED  = "EVALUATED"    # AI evaluation done


# ============================================================
# Answer type — text typed or voice recorded
# ============================================================
class AnswerType(str, enum.Enum):
    TEXT  = "TEXT"
    VOICE = "VOICE"


# ============================================================
# Question category
# ============================================================
class QuestionCategory(str, enum.Enum):
    TECHNICAL       = "TECHNICAL"
    BEHAVIORAL      = "BEHAVIORAL"
    PROBLEM_SOLVING = "PROBLEM_SOLVING"


# ============================================================
# TABLE 1: interview_sessions
# One row per candidate+job interview attempt.
# Created automatically after semantic matching completes.
# ============================================================
class InterviewSession(Base):
    __tablename__ = "interview_sessions"

    id                   = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # Link to candidate profile (Phase 2)
    candidate_profile_id = Column(
        Integer, ForeignKey("candidate_profiles.id"),
        nullable=False, index=True
    )

    # Link to the job being interviewed for
    job_id               = Column(
        Integer, ForeignKey("jobs.id"),
        nullable=False, index=True
    )

    # Current lifecycle status
    status               = Column(Enum(SessionStatus), default=SessionStatus.PENDING)

    # Overall interview score (0-100), set after evaluation
    interview_score      = Column(Float, nullable=True)

    # AI-generated overall feedback after evaluation
    overall_feedback     = Column(Text, nullable=True)

    # Strengths and weaknesses from evaluation
    strengths            = Column(Text, nullable=True)
    weaknesses           = Column(Text, nullable=True)

    # Final recommendation after interview
    recommendation       = Column(String(50), nullable=True)

    # Was interview done via voice or text?
    interview_mode       = Column(String(10), default="TEXT")

    started_at           = Column(DateTime(timezone=True), nullable=True)
    completed_at         = Column(DateTime(timezone=True), nullable=True)
    created_at           = Column(DateTime(timezone=True), server_default=func.now())
    updated_at           = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    candidate_profile    = relationship("CandidateProfile")
    job                  = relationship("Job")
    questions            = relationship(
        "InterviewQuestion",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="InterviewQuestion.order_index"
    )

    def __repr__(self):
        return f"<InterviewSession id={self.id} candidate={self.candidate_profile_id} status={self.status}>"


# ============================================================
# TABLE 2: interview_questions
# AI-generated questions for a session.
# Each question belongs to one session.
# ============================================================
class InterviewQuestion(Base):
    __tablename__ = "interview_questions"

    id           = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # Parent session
    session_id   = Column(
        Integer, ForeignKey("interview_sessions.id"),
        nullable=False, index=True
    )

    # The question text generated by Groq LLM
    question_text = Column(Text, nullable=False)

    # Category of question
    category      = Column(Enum(QuestionCategory), default=QuestionCategory.TECHNICAL)

    # Display order within the session (1, 2, 3...)
    order_index   = Column(Integer, default=1)

    # Path to generated TTS audio file for this question
    audio_path    = Column(String(500), nullable=True)

    # Has the candidate answered this question?
    is_answered   = Column(Boolean, default=False)

    created_at    = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    session       = relationship("InterviewSession", back_populates="questions")
    answer        = relationship(
        "InterviewAnswer",
        back_populates="question",
        uselist=False,
        cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"<InterviewQuestion id={self.id} session={self.session_id} order={self.order_index}>"


# ============================================================
# TABLE 3: interview_answers
# Candidate's answer to one interview question.
# One answer per question — text or voice transcription.
# ============================================================
class InterviewAnswer(Base):
    __tablename__ = "interview_answers"

    id            = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # Which question this answers
    question_id   = Column(
        Integer, ForeignKey("interview_questions.id"),
        nullable=False, unique=True, index=True
    )

    # The session this answer belongs to
    session_id    = Column(
        Integer, ForeignKey("interview_sessions.id"),
        nullable=False, index=True
    )

    # Text of the answer (typed or transcribed from voice)
    answer_text   = Column(Text, nullable=True)

    # How the answer was provided
    answer_type   = Column(Enum(AnswerType), default=AnswerType.TEXT)

    # Path to uploaded voice recording (if voice answer)
    audio_path    = Column(String(500), nullable=True)

    # AI evaluation fields (filled after evaluation phase)
    answer_score  = Column(Float, nullable=True)    # 0-100
    ai_feedback   = Column(Text, nullable=True)     # per-answer feedback
    is_evaluated  = Column(Boolean, default=False)

    # Semantic similarity between answer and expected content
    semantic_score = Column(Float, nullable=True)

    submitted_at  = Column(DateTime(timezone=True), server_default=func.now())
    updated_at    = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    question      = relationship("InterviewQuestion", back_populates="answer")
    session       = relationship("InterviewSession")

    def __repr__(self):
        return f"<InterviewAnswer id={self.id} question={self.question_id} score={self.answer_score}>"